language: scala
scala: 2.11.1
jdk:
- oraclejdk7
- openjdk7
- openjdk6
install:
- echo `git rev-list rev-base..HEAD --count`
- set
- ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
branches:
  only: rev
env:
  global: TERM=dumb
deploy:
  provider: releases
  api_key:
    secure: AMxrTryOhCRw9x94oa1bSQffsf73oUoDoFW7UQlnGtWyfPbsoL5ftuNiz/FSfq5nS9Tp35nRojjUTyPqt08GPiuNpK4GpNNm29p6xcbtE4rvkMUZrqRXZ0c4lVb5dk4XQk7WM8jH4eCPCg2Jssl/g9h2plqfxrThO/RAYyPK9PA=
  file: build/libs/*.jar
  on:
    repo: target-san/Gateway
    jdk:  oraclejdk7
